# Changes here will be overwritten by Copier
AnswerStrategy: recommended
Authors: Hugo Solleder <hugo.solleder@epfl.ch>
CodeOfConductContact: hugo.solleder@epfl.ch
ConfigIndentation: 2
JuliaIndentation: 4
JuliaMinVersion: '1.10'
License: GPL-3.0
LicenseCopyrightHolders: Hugo Solleder
MarkdownIndentation: 2
PackageName: UrbanTethysChloris
PackageOwner: EPFL-ENAC
PackageUUID: 8ae36e77-b357-5cab-a873-ceeadc1a5254
_commit: v0.15.0
_src_path: https://github.com/JuliaBesties/BestieTemplate.jl
